apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  params:
    - name: image_url
      description: the image url
  workspaces:
  - name: pipeline-pvc
  tasks:  
    - name: print-default-versions
      taskRef:
        name: print-versions-task
      params:
        - name: image_url
          value: $(params.image_url)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
