apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: image_url
      description: The image_url
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: main-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: image_url
          value: $(params.image_url)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bindingvbi2
spec:
  params:
    - name: image_url
      value: "icr.io/continuous-delivery/pipeline/pipeline-base-image:2"
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: bindingvbi3
spec:
  params:
    - name: image_url
      value: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: vbi2-listener
spec:
  triggers:
    - binding:
        name: bindingvbi2
      template:
        name: template
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: vbi3-listener
spec:
  triggers:
    - binding:
        name: bindingvbi3
      template:
        name: template
