apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-versions-task
spec:
  params:
    - name: image_url
      description: the image url
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: print-versions
      image: $(params.image_url)
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - |
        echo "DEBUG | devsecops_pipeline_metrics={\"ibm_toolchain_pipeline_cd_change_request_check_deployment_readinees_seconds\": 54, \"ibm_toolchain_pipeline_cd_change_request_create_seconds\": 25, \"ibm_toolchain_pipeline_cd_change_request_check_approval_seconds\": 10, \"ibm_toolchain_pipeline_cd_change_request_implement_seconds\": 122}"
        echo "test"
        echo "DEBUG | devsecops_pipeline_metrics={\"ibm_toolchain_pipeline_cd_change_request_check_deployment_readinees_seconds\": 5, \"ibm_toolchain_pipeline_cd_change_request_create_seconds\": 15, \"ibm_toolchain_pipeline_cd_change_request_check_approval_seconds\": 45, \"ibm_toolchain_pipeline_cd_change_request_implement_seconds\": 12}"

