apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-versions-task
spec:
  params:
    - name: image_url
      description: the image url
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: print-versions
      image: $(params.image_url)
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - default_versions.sh
