apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vserv-eu.sos.ibm.com:8200"
      path: ""
      version: "v1"
      auth:
        appRole:
          path: "approle"
          roleId: "8e846534-27f0-6b2b-326d-9ee0dffeda34"
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "secure-properties"
            key: "secret_id"
