apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigpropbinding
spec:
  params:
  - name: merge-environment-properties
    value: deploy-trigger-envprops
  - name: merge-secure-properties
    value: deploy-trigger-secret
