apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-registry-ctask
spec:
  workspaces:
  - name: output
    mountPath: /workspace
  steps:
  - name: cleanup-registry
    image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.32
    imagePullPolicy: IfNotPresent
    workingDir: /workspace
    command: ["/bin/bash", "-c"]
    args:
      - |
        #!/usr/bin/env bash
        echo "hello world"