apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-cleanup-registry
spec:
  params:
    # CD integration
    - name: api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: region
      description: the ibmcloud region containing the toolchain referencing the repository
      default: us-south

  resourcetemplates:
    # CD context defined as a configmap and secret because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.REGION)
        OPTIONS: $(params.OPTIONS)
        REGISTRY_NAMESPACE: $(params.REGISTRY_NAMESPACE)

    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.API_KEY)

    # k8s resources to be able to pull docker image from a specific container registry
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: cleanup-registry-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  15Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        #generateName: $(params.charts_branch)-base-run
        name: cleanup-registry-$(uid)
        labels:
          triggertemplated: "true"
          generatedBy: "trigger-template-ci"
      spec:
        pipelineRef:
          name: pipeline-cleanup-registry
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: cleanup-registry-$(uid)-pvc
        serviceAccountName: docker-build-sa
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cleanup-registry
spec:
  triggers:
    - binding:
        name: trigger-binding-cleanup-registry
      template:
        name: trigger-template-cleanup-registry
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-cleanup-registry
spec:
  params:
    - name: source_repo
      value: 1234