apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build
spec:
  params:
    - name: source_repo
    - name: source_branch
    - name: source_directory
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-source-repo
      taskRef:
        name: git-clone-repo
      params:
        - name: repository
          value: $(params.source_repo)
        - name: branch
          value: $(params.source_branch)
        - name: directory-name
          value: $(params.source_directory)
        - name: continuous-delivery-context-secret
          value: cd-secret
        - name: ibmcloud-apikey-secret-key
          value: API_KEY
      workspaces:
      - name: output
        workspace: pipeline-pvc  
    - name: build
      taskRef:
        name: build-task
      runAfter: [clone-source-repo]  
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageName
          value: test
        - name: imageTag
          value: "1.0"
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
    - name: validate
      taskRef:
        name: validate-task
      runAfter: [build-task]  
      params:
        - name: source_directory
          value: $(params.source_directory)
        - name: imageName
          value: test
        - name: imageTag
          value: "1.0"
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc        