apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipeline-run-
spec:
  pipelineRef:
    name: pipeline-build
  taskRunSpecs:
  - pipelineTaskName: build
    imagePullSecrets:
    - name: private-registry-secret
  - pipelineTaskName: validate
    imagePullSecrets:
    - name: private-registry-secret
