apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
  workspaces:
  - name: pipeline-pvc
  tasks:  
    - name: build-task
      taskRef:
        name: task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
