apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
  tasks:  
    - name: build-task-nosc
      taskRef:
        name: build-task-nosc
    - name: build-task-sc
      taskRef:
        name: build-task-sc
   
