apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task-nosc
  annotations:
    io.kubernetes.cri.untrusted-workload: "false"
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
  stepTemplate:
    env:
      - name: THUNDERDOME_API_KEY
        valueFrom:
          secretKeyRef:
            name: secure-properties
            key: THUNDERDOME_API_KEY
  volumes:
    - name: ovpn
      secret:
        secretName: cd-secret
  steps:
    - name: connectcluster
      image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.61
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          bx login --apikey ${THUNDERDOME_API_KEY} -r us-south;
          bx cs clusters;
          bx cs cluster config --cluster airgapped-poc;
          kubectl get ns;
          kubectl get pods -A;
        
