apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: main-pipeline
spec:
  tasks:  
    - name: build-task-nosc
      taskRef:
        name: build-task-nosc
    - name: build-task-sc
      taskRef:
        name: build-task-sc
    - name: build-task-dind-sc
      taskRef:
        name: build-task-dind-sc
   
