apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
  annotations:
    io.kubernetes.cri.untrusted-workload: "false"
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
  volumes:
    - name: ovpn
      secret:
        secretName: cd-secret
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REVISION
          value: $(params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          sleep 5m;
  sidecars:
  - image: dperson/openvpn-client
    name: openvpn-side
    volumeMounts:
    - name: ovpn
      mountPath: /etc/ovpnconfig
      subPath: OVPN_FILE
      readOnly: true
    command: ["/bin/bash", "-c"]
    args:
      - |
        openvpn --config /etc/ovpnconfig
