apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: deploytemplate
spec:
  params:
    - name: cluster
      description: the cluster
    - name: localrun_aes
      description: local key
  resources:
    inputs:
      - name: cluster
        type: cluster
        description: "(Optional) The cluster used for Docker build"
        optional: true
    outputs:
      - name: built-image
        type: image
        description: "(Optional) The image to build"
        optional: true
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: deploy-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: cluster
          value: $(params.cluster)
        - name: anothervalu
          value: $(params.anothervalu)
        - name: localrun_aes_key
          value: $(params.localrun_aes_key)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: repobinding
spec:
  params:
    - name: cluster
      value: "bog-cluster"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: deploy-listener
spec:
  triggers:
    - binding:
        name: repobinding
      template:
        name: deploytemplate
