apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: cluster
      description: the cluster
    - name: anothervalu
      description: the valu
    - name: localrun_aes_key
      description: localrun_aes_key
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
        - name: ANOTHERV
          value: $(params.anothervalu)
        - name: LOCALRUN
          value: $(params.localrun_aes_key)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Hey $LOCALRUN"
          echo "Deploying to $CLUSTER";
          echo "Oh and $ANOTHERV";
          sleep 60s;
          echo "Small Pause!";
          sleep 120s;
          echo "Done!";
          for i in {1..3} ; do
          echo "Round $i";
          ls;
          sleep 30s;
          done
