apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:
    - name: cluster
      description: the cluster to deploy to
    - name: anothervalu
      description: another val
    - name: localrun_aes_key
      description: localrun_aes_key
  workspaces:
  - name: pipeline-pvc
  tasks:  
    - name: deploy-with-kubectl
      taskRef:
        name: deploy-with-kubectl
      params:
        - name: cluster
          value: $(params.cluster)
        - name: anothervalu
          value: $(params.anothervalu)
        - name: localrun_aes_key
          value: $(params.localrun_aes_key)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc  

