apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: cluster
      description: the cluster
    - name: anothervalu
      description: the valu
    - name: localrun_aes_key
      description: localrun_aes_key
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
        - name: ANOTHERV
          value: $(params.anothervalu)
        - name: LOCALRUN
          value: $(params.localrun_aes_key)
        - name: TESTVAR
          valueFrom:
            configMapKeyRef:
              name: environment-properties
              key: simpleTriggerProperty
              optional: true   
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: git_token
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "--> $TESTVAR"
          echo "Hey $LOCALRUN"
          echo "Deploying to $CLUSTER";
          echo "Oh and $ANOTHERV";
          sleep 2s;
          echo "Small Pause!";
          sleep 3s;
          echo "Done!"
          echo "$GIT_TOKEN" | cut -c1-10