apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-with-kubectl
spec:
  params:
    - name: cluster
      description: the cluster
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: deploy
      image: thebog/privatebog:alpine
      imagePullPolicy: Always
      env:
        - name: CLUSTER
          value: $(params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          echo "Deploying to $CLUSTER";
          sleep 2s;
          echo "Small Pause!";
          sleep 3s;
          echo "Done!";
          for i in {1..2} ; do
          echo "Round $i";
          ls;
          sleep 5s;
          done
          sleep 3610s;
